name: GetResource build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.GoogleBigQuery.GetResource/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.GoogleBigQuery.GetResource
      env_var_name_1: BigQuery_SecretJson
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.BIGQUERY_SECRETJSON }}